% Generated by ngen.
% SPDX-License-Identifier: LGPL-3.0-or-later
% Module version. Single source of truth: the "version" field of module.json
% (kept in sync by nmm and the build), read at call time - not duplicated here.
function v = morse_version()
  info = jsondecode(fileread([modulepath('morse'), '/module.json']));
  v = info.version;
end
