%=============================================================================
% Generated by ngen. Makes this module a first-class nmm local module so it can
% be installed, packaged and published (nmm install / package / publish).
%=============================================================================
% LICENCE_BLOCK_BEGIN
% SPDX-License-Identifier: LGPL-3.0-or-later
% LICENCE_BLOCK_END
%=============================================================================
% A pure-.m (macro) module has no native code to compile: the builder only
% (re)generates the loader and builds the help so nmm has a complete, loadable
% module to lock and register.
NGEN_MODULE_DIR = fileparts(nfilename('fullpath'));
nmm_build_loader('morse', NGEN_MODULE_DIR);
nmm_build_help('morse', NGEN_MODULE_DIR);
clear('NGEN_MODULE_DIR');
%=============================================================================
