% Generated by ngen.
% SPDX-License-Identifier: LGPL-3.0-or-later
if isdir([modulepath('morse'), '/locale'])
  [status, message] = i18nHelpers('unregister', 'morse');
  if ~status
    warning(message);
  end
end
rmpath([modulepath('morse'), '/functions']);
