% Generated by ngen.
% SPDX-License-Identifier: LGPL-3.0-or-later
addpath([modulepath('morse'), '/functions'], '-frozen');
if isdir([modulepath('morse'), '/locale'])
  [status, message] = i18nHelpers('register', 'morse', modulepath('morse'));
  if ~status
    warning(message);
  end
end
